class ZFSM abstract{    
    private
    Name DefaultState;

    protected
    Name __State__;

    virtual
    protected
    ZFSM Init(Name DefaultState='Idle'){
        self.DefaultState=DefaultState;
        return self;
    }

    virtual
    bool Set(Name NewState)
    {return __State__=NewState;}

    virtual
    void Tick(){}

    Name State()
    {return (__State__=='')?DefaultState:__State__;}
}