class ZReactor{
    private
    double __Strength__;

    bool New;

    uint Cooldown;

    Name ID;

    ZStimulus CurrStim;

    virtual
    bool React(ZStimulus Stim){
        if(CurrStim && CurrStim!=Stim && CurrStim.SimilarTo(Stim))
            __Strength__+=CurrStim.Strength;
        else if(Cooldown || (CurrStim && CurrStim.Strength+__Strength__>Stim.Strength))
            return false;
        Cooldown+=Stim.Persistence;
        CurrStim=Stim;
        New=true;
        return !(__Strength__=0);
    }

    virtual
    void Tick(){
        if(New)
            New=false;
        if(CurrStim){
            if(Cooldown)
                Cooldown=Max(Cooldown-1, 0);
            if(!Cooldown || !CurrStim.Decay)
                CurrStim=null;
        }else Cooldown=0;
    }

    virtual
    double Strength()
    {return (CurrStim)?CurrStim.Strength+__Strength__:0;}
}