struct JetpackStats{
	int //General
		JetpackPower,
		JetpackCost;

	double //Jetpack
		   JetpackControl;
}

extend
class ZArmor{
	protected
	int //Jetpack
		JetpackPower;

	virtual
	void InitJetpack(ArmorSlot Slot, in out JetpackStats Stats){
		JetpackPower=Stats.JetpackPower;
		if(Slot==AMR_FEET){
			JetpackWaiter=0;
			JetpackCost=Stats.JetpackCost;
			JetpackControl=Stats.JetpackControl;
		}
	}
}

#include "ZSCRIPT/Z/INV/ARMOR/JETPACK/JETPACK.zsc"