class ZStats:Thinker{
    double ActualYaw,
           ActualPitch,
           ActualRoll,
           Shake;

    static
    ZStats Instance(){
        ThinkerIterator it=ThinkerIterator.Create('ZStats', STAT_STATIC);
        ZStats Result=ZStats(it.Next());
        if(!Result)
            Result=ZStats.Create();
        return Result;
    }

    static
    ZStats Create(){
        ZStats Result=new('ZStats');
        Result.ChangeStatNum(STAT_STATIC);
        return Result;
    }
}