extend
class ZMatrix2{
    static
    ZMatrix2 Identity_2D()
    {return Identity(3);}

    static
    ZMatrix2 FromAngle(double Angle){
        ZMatrix2 Result=Identity_2D();
        until(-360<Angle && Angle<360)
            Angle%=360;
        Result.Set(0, 0,  Cos(Angle));
        Result.Set(0, 1,  Sin(Angle));
        Result.Set(1, 0, -Sin(Angle));
        Result.Set(1, 1,  Cos(Angle));
        return Result;
    }
}