class ZArray
{Array<Object> _;}

class ZArray_String{
	Array<String> _;
	Array<String> __;

	void V2Push(Vector2 Point){
		_.Push(Point.X.."");
		__.Push(Point.Y.."");
	}
}

class ZIterator{
	private
	int Iter;

	private
	ZArray Array;

	static
	ZIterator Create(ZArray Array){
		ZIterator Iterator=new("ZIterator");
		Iterator.Iter=0;
		Iterator.Array=Array;
		return Iterator;
	}

	Object Next()
	{return Array._[Iter++];}
}