class ZF_ILinear:ZF_Interpolator{}

class ZF_Interpolator:ZF_Base{
    ZF_Base Start,
            End;
    static
    ZF_Interpolator Create(Name Type, ZF_Base Start, ZF_Base End){
        ZF_Interpolator Result=ZF_Interpolator(ZF_Base.Create('I'..Type));
        Result.Start=Start;
        Result.End=End;
        return Result;
    }

    override
    double Apply(double X) const
    {return (1-X)*Start.Apply(super.Apply(X))+X*End.Apply(super.Apply(X));}
}