class ZReactor play abstract{
    private
    double __Strength__;

    bool __New__;

    uint Cooldown;

    Name ID;

    ZStimulus CurrStim;

    virtual
    bool React(ZStimulus Stim){
        if(!IsValid(Stim))
            return false;
        if(CurrStim && CurrStim!=Stim && CurrStim.SimilarTo(Stim))
            __Strength__+=CurrStim.Strength;
        else if(Cooldown || (CurrStim && CurrStim.Strength+__Strength__>Stim.Strength))
            return false;
        else __Strength__=0;
        Cooldown+=Stim.Persistence;
        CurrStim=Stim;
        __New__=true;
        return !(__Strength__=0);
    }

    virtual
    void Tick(){
        if(__New__)
            __New__=false;
        if(CurrStim){
            if(Cooldown)
                Cooldown=Max(Cooldown-1, 0);
            if(!Cooldown || !CurrStim.Decay)
                CurrStim=null;
        }else Cooldown=0;
    }

    virtual
    bool IsValid(ZStimulus Stim)
    {return true;}

    virtual
    double Strength()
    {return Min(__Strength__, STR_MAX);}

    virtual
    void Reset(){
        __Strength__=Cooldown=__New__=CurrStim=null;
        ID='';
    }
}