class ZWeapons:ZRegistry{
    bool Add(ZWeapon ZWeapon)
    {return ZWeapon && super.Add(ZWeapon);}
    
    ZWeapon Get(Name Name) const
    {return ZWeapon(super.Get(Name));}
    
    ZWeapon GetRand() const
    {return ZWeapon(super.GetRand());}
}

class ZWeapon:ZItem{
    int Damage,
        Durability,
        MaxDurability;

    clearscope
    int, int GetDurability() const
    {return Durability, MaxDurability;}
}